# -*- coding: utf-8 -*-
"""HW_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_Rt_ax7-ArM9gNB6HUjbFTe2ADEMPpz
"""

## HW_Q1 Answer =  144

## HW_Q2

import matplotlib.pyplot as plt
import numpy as np

def learning_curve (Hs,Ts,filename):
  score = np.zeros(40)
  for i in range(0, 40):
    iter = i*50+50
    score[i] = test_NN(Ts, Hs, iter)

  iter_array=np.linspace(50,2000,40)
  plt.plot(iter_array,score)
  plt.savefig(str(filename)+".png")

